apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: staking-indexer
  namespace: staking-indexer
spec:
  interval: 1m
  chart:
    spec:
      chart: boilerplate
      version: "0.6.0"
      sourceRef:
        kind: HelmRepository
        name: aws-ecr
        namespace: flux-system
      interval: 3m
  values:
    namespace: staking-indexer
    name: staking-indexer
    deployment:
      image: 490721144737.dkr.ecr.us-east-1.amazonaws.com/staking-indexer
      version: 106ab4fafeeb5281477829df53628652dd554283
      replicas: 1
      ports:
        - protocol: TCP
          containerPort: 2112
          name: prom
      volumes:
        - name: staking-indexer-configmap
          configMap:
            name: staking-indexer
        - name: phase1-global-configmap
          configMap:
            name: phase1-global-config
        - name: staking-indexer-configs
          emptyDir: {}
        - name: staking-indexer
          persistentVolumeClaim:
            claimName: staking-indexer
      volumeMounts:
        - name: staking-indexer-configmap
          mountPath: /tmp/staking-indexer
        - name: phase1-global-configmap
          mountPath: /tmp/global
        - name: staking-indexer-configs
          mountPath: /home/staking-indexer/.sid
        - name: staking-indexer
          mountPath: /home/staking-indexer/.sid/data
      command: |
        sid start
      env:
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: staking-indexer
              key: rabbitmqUsername
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: staking-indexer
              key: rabbitmqPassword
        - name: BTCNODE_USER
          valueFrom:
            secretKeyRef:
              name: staking-indexer
              key: btcnodeUser
        - name: BTCNODE_PASS
          valueFrom:
            secretKeyRef:
              name: staking-indexer
              key: btcnodePass
      nodeSelector:
        workload: "btc"
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "2112"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        configmap.reloader.stakater.com/reload: "staking-indexer, phase1-global-config"
      securityContext:
        fsGroup: 1138
      initContainer:
        enabled: true
        image: 490721144737.dkr.ecr.us-east-1.amazonaws.com/infra-toolkit
        version: v0.0.7
        command: |
          STAKING_INDEXER_DIR=/home/staking-indexer/.sid
          cp /tmp/staking-indexer/sid.conf $STAKING_INDEXER_DIR/sid.conf
          sed -i "s/^User =.*/User = $RABBITMQ_USERNAME/" $STAKING_INDEXER_DIR/sid.conf
          sed -i "s/^Password =.*/Password = $RABBITMQ_PASSWORD/" $STAKING_INDEXER_DIR/sid.conf
          sed -i "s/^RPCUser =.*/RPCUser = $BTCNODE_USER/" $STAKING_INDEXER_DIR/sid.conf
          sed -i "s/^RPCPass =.*/RPCPass = $BTCNODE_PASS/" $STAKING_INDEXER_DIR/sid.conf
          cp /tmp/global/global-params.json $STAKING_INDEXER_DIR/global-params.json
    service:
      enabled: true
      type: NodePort
      ports:
        - protocol: TCP
          port: 2112
          targetPort: prom
          name: prom
    persistence:
      enabled: true
      storageClassName: "ebs-sc"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    ingress:
      enabled: false
    purgeCloudflareCache:
      enabled: false
    encryptedConfig:
      btcnodePass: AgBpcW5ZG013yAJqaV847ODkI2gbQLWaQvxzSm45MspUYYzXreWnxDmYmXoe0PZpvF1HoaY9H0SYYmL2d0VYGWsaZ3Wh1Jyjm/sYDoTUqdlkGkVdR7JN4cOcpnAjaSIgrKoyk+RMJUUa2uvc+TkIJb+USwaAgahMFao0hZ1cViTySXZgpwody1UZdC0qCMBfgEPdPvP9j8zoWLgop4O5F9iDUczAcvzdkRu3NxWXeseqoIB0WoYnFGvqfgLfRwL4F66lD9zzFgPF7iyVQTGZ6zNwBZAOEUeJXpvXPHT7Y3uWjTt2vSJgOoHHNgDK4topkxIK8/WHvC8JoD2i+XL3RX/C72bWfllKtp6LUVZ5nG0artH1AztVdu2c3wgfWxwmbkt24rprY4hKTYhyE+wgkh/QNCf/RwudQkUBE0+U+4l9UmTnF9KOPH/dPqpVaPF0JQTFV6NgB3B26Zh7xy+MInIo46RHvBjwoPOkpu5IVvkdW29WfoDFLo+RQNQsBBsv7b7vGH84t/wwik0u1VWpCMNpSO4lrZtMFomCw7U0nCn/hMgXJjsX6T6aMXUw4muuO3KJw+I+ydDVlGcF2is744ZoAxBMTRnMmivFEO3xJi5bSQLzw7JptX5vAEHmwZSmnXsaj8sbs8M6aoVUrbnIKEssY9Im0WE/74eF4hCuGQEoWhBTQJ+E79cJfH4W+maxYEdhhhxMkHaz6A==
      btcnodeUser: AgBLESVE6eQGp+omn/GFNiDctCbdQchnxHxwvMjSOxibb99TmGlsblXdBmGGhkuYYcjDE8bqAesScm68nRgmmQjwqaDjZFguerYk09zlJBjQVlEtbrKz0YCiKTOfZ4Jv13cym31NvBBMAh111s3PmkW8AeEWZtCmBSUvALvaHeU/ZHFGixpLt5Y8LbdqnoGGXjT+gFHUZBzhqD+WnBvwJfolm7jpt983BT+udQagEQr9lwjABLbDXQUcB8ncCmbu0ofUfvOlWPKoRNOBQ2TYt/x55dvGYoonM7DJa66/v6DwOw6/0Xiy5y0oEOxkNcnshCFCN2zob2IpuCTu3KXW/ORzab1So/lWVn4wILEsv290WQxNZ6mrJE6HAWhxAk5eYEbRll71m+5rBblV+KZXmkS09+cHQ6rRlMRieO7/mDctOzqi2/NBnG8TN/4fKR2E4XCR1xcLoHsqv+R8eizhJSQp1HRzep5oLM9QF/Q6EoXYye5fwTDcS+Q3D/GCW5X9CfS3rmSjVXwmFeg8Ed8qtq/5tyOKx6qGiCLJ7Sx6y25rSSHZzzgwRxJl5NkP1h3qEfBvxa0tFgNYXmeNAgptVdyuGGGbJ6W/HeHyBxtivoelc2ReuRUobOBCwtdQAFFghDg5llaVuu6gw9FSbUdNLD1fChIwuySEeWDuq5mmMOevDeTvDK88hScO1ZbpZA5NZI1c2IBMb+Cuyg==
      rabbitmqPassword: AgCeJinUPFC+7FsRPTrPxZCMqXgtdXyOURwBTuF5h4FSuVcwUpzbJwycFjeMfHSSg4dMIQ7FdNPt33SnFvc2U+I+lN3DZ2X4rX5SQYR0dSNw/0gUJP7A75fHUuXphArxkqhwfV9kyyyCZ5gyQ+loKBU2LcRdbdCrASHBvofsFdFFeYqR9Nwc98eu45HF23lxar6SQJfj5u9Zg9zqmGL8QwWtUgAKrW4rKI2dsBU29YXlIwliC4MVkEW+y8SXZpRbawW4OvvnyYF8v6Hei3h6N7uTsT8u2I2wwPknoDR7Ht15aIzIrfBv0OeqP8UHVbu+FtFgUVe0gWgqsTM4IfSseZ0CAb/C8dwtHEUmI9LxDAxCWBFLP7mHSZdHSMBo3ia/DoPOaCDu2ysFXHO6UlUYi47W854nQq7kIuqWS697pDgBXGeFdZkO8jDQt6OQMGKCJfAVY6SXmMcxxXm4n0pwaNuHJJ6HLt7MZtRl08lHMYLTxGcGcM8GKiEHPK1s5ZEcjj5TXTFI0L5/5IAl3oyBt5Qko1ubOGmr+VfDwwzX14mM1oNYb7N2rinfCKrA3q3v0N9cWVaTDwAspGReW9UzT7RFiFb9Adtuao7lpnfCJ2UN+RAsLm3Tp0q3uV9D3otwLO+7tDY7+kSYFxyPBpHnPaDOE+glXFwhZe6W+wjsgG1Kt/o0IKONqMJ6PsI2FUykCAiiMWix3YUTrpJ6NeDN/mz32/Xzzt9QvwMGG88hlE5dpg==
      rabbitmqUsername: AgCD1kwVPTRStkUPBcsuRXVBMWqhRIJJRLHPbLi5AnOJcNaqIhCqL8fDpLDbKVv2BidvYHnHvOP82O4JwJ8oyD0NR+DoAJwga6+RgFFL8qngerstspr8R90vJk+/RsoLYYSK+KOQaq/67OpEZdvlGUC4UlyqdFpXIubMWyq8xlBjWrJ8YaSwVUxrVThARQPpY5W49bCq6NoRbwJG0ALpYCgllPD+kPP4bWFLfov7j1KCyBjEPkScgXPaDMJEXSaXuIb5qPvODktD2VzgK2wOsomn5eC7d9NcmwSyE1TSp0G+6ogqpvoUtPdsq2/vuoX22ax66lzx1fdw1ApmaRYtyp9mfJ0UzWzpQwtqDTkZsvobl0OzQ4Fp/9ZH8sMikKw5lyLXvc2j9QhxmaTjvHO0omcQ61it0gb6YsousroA+XpXBni5sfMJMxXjKCX5QjiSHS8HekVV3AJScjc9oojVkjqaKG+qDaOiGz5SBoO7+nddInAfNOl6tvoNxOZjfna4aTCIzfahyvPSwXB3d8luAcbfHCiAHBw1lkTg0mMLI/QRgwAKwAMXBSYLVGpETQ1V30gD3tdHCCcqRtYE65S0xdVBmup0dY+YxyrZgLl/3JggskEFAzWJycJn+DTzA6/9Qm29EV3Iy5ynNPToAo1Wq934MRIjrew00nI5Nc/gxBZKogwNwSh14bnmngs/yHfvSy87rTpQKDgPaQ==
    configFiles:
      sid.conf: |
        [Application Options]
        ; Logging level for all subsystems {trace, debug, info, warn, error, fatal}
        LogLevel = debug

        ; Bitcoin network to run on {mainnet, regtest, testnet, signet}
        BitcoinNetwork = regtest

        [btcconfig]
        ; The daemon's rpc listening address
        RPCHost = bitcoind-regtest-lb.bitcoind-regtest:18442/wallet/regtest

        ; Username for RPC connections
        RPCUser =

        ; Password for RPC connections
        RPCPass =

        ; The maximum number of peers staker will choose from the backend node to retrieve pruned blocks from. This only applies to pruned nodes.
        PrunedNodeMaxPeers = 0

        ; The interval that will be used to poll bitcoind for new blocks. Only used if rpcpolling is true.
        BlockPollingInterval = 30s

        ; The interval that will be used to poll bitcoind for new tx. Only used if rpcpolling is true.
        TxPollingInterval = 10s

        ; size of the Bitcoin blocks cache
        BlockCacheSize = 20971520

        MaxRetryTimes = 5

        RetryInterval = 0.5s

        [dbconfig]
        ; The directory path in which the database file should be stored.
        DBPath = /home/staking-indexer/.sid/data

        ; The name of the database file.
        DBFileName = bbolt.db

        ; Prevents the database from syncing its freelist to disk, resulting in improved performance at the expense of increased startup time.
        NoFreelistSync = true

        ; Specifies if a Bolt based database backend should be automatically compacted on startup (if the minimum age of the database file is reached). This will require additional disk space for the compacted copy of the database but will result in an overall lower database size after the compaction.
        AutoCompact = false

        ; Specifies the minimum time that must have passed since a bolt database file was last compacted for the compaction to be considered again.
        AutoCompactMinAge = 168h0m0s

        ; Specifies the timeout value to use when opening the wallet database.
        DBTimeout = 1m0s

        [queueconfig]
        ; the user name of the queue
        User =

        ; the password of the queue
        Password =

        ; the url of the queue
        Url = rabbitmq-headless.rabbitmq:5672

        ; the process timeout of the queue
        ProcessingTimeout = 5s

        ; the maximum number of times a message will be retried
        MsgMaxRetryAttempts = 10

        ; the time a message will be hold in delay queue before being sent to main queue again
        ReQueueDelayTime = 300s

        [metricsconfig]
        ; IP of the Prometheus server
        Host = 0.0.0.0

        ; Port of the Prometheus server
        Port = 2112